### ISSUE TITLE
CTS._getText should return stripped text

### ISSUE THREAD

**Issue by balmas** [Capitains/Sparrow#79]
CTS.getText leaves new lines in place of the removed nodes. We should probably trim/normalize all the whitespace. It's possible this isn't desirable in all cases but for the most part it should be safe.

**Comment by balmas** [comment]
maybe just  `$.trim(data.getText().replace(/(\r\n|\n|\r)/gm,"").replace(/\s+/gm," "))`

**Comment by PonteIneptique** [comment]
Maybe as an option ?
